In [6]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [7]:
dataset = pd.read_csv('data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [8]:
print(x)

[['Italy' 'Italy' 'week' ... 15531.0 0.0 0.0]
 ['Italy' 'Italy' 'week' ... 15664.0 -174.0 -1.11082737487231]
 ['Italy' 'Italy' 'week' ... 15283.0 -318.0 -2.08074330955963]
 ...
 ['Switzerland' 'Switzerland' 'week' ... 1215.0 23.6999999999998
  1.9506172839506]
 ['Switzerland' 'Switzerland' 'week' ... 1184.0 4.79999999999995
  0.405405405405417]
 ['Switzerland' 'Switzerland' 'week' ... 1141.0 10.5 0.920245398773005]]


In [13]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [14]:
print(x_train)

[['Spain' 'Melilla' 'week' ... 10.0 1.0 10.0]
 ['UK' 'Northern Ireland' 'week' ... 271.0 -13.0 -4.79704797047971]
 ['Brazil' 'Manaus' 'week' ... 227.0 701.0 308.810572687224]
 ...
 ['UK' 'South East' 'week' ... 1757.0 77.0 4.38247011952191]
 ['Chile' 'Ñuble' 'week' ... 61.0 15.0 24.5901639344262]
 ['Ecuador' 'Guayas' 'week' ... 356.0 -27.0 -7.58426966292134]]


In [15]:
print(x_test)

[['Chile' 'Coquimbo' 'week' ... 90.0 -22.0 -24.4444444444444]
 ['UK' 'England And Wales' 'week' ... 9228.0 0.0 0.0]
 ['US' 'Michigan' 'week' ... 1899.0 -12.0 -0.631911532385458]
 ...
 ['UK' 'East' 'week' ... 988.0 16.0 1.61943319838056]
 ['Chile' 'Coquimbo' 'week' ... 68.0 13.0 19.1176470588235]
 ['US' 'US' 'week' ... 50672.0 0.0 0.0]]


In [17]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [18]:
print(x)

[['Italy' 'Italy' 'week' ... 15531.0 0.0 0.0]
 ['Italy' 'Italy' 'week' ... 15664.0 -174.0 -1.11082737487231]
 ['Italy' 'Italy' 'week' ... 15283.0 -318.0 -2.08074330955963]
 ...
 ['Switzerland' 'Switzerland' 'week' ... 1215.0 23.6999999999998
  1.9506172839506]
 ['Switzerland' 'Switzerland' 'week' ... 1184.0 4.79999999999995
  0.405405405405417]
 ['Switzerland' 'Switzerland' 'week' ... 1141.0 10.5 0.920245398773005]]


In [19]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [20]:
print(x)

[[0.0 0.0 0.0 ... 15531.0 0.0 0.0]
 [0.0 0.0 0.0 ... 15664.0 -174.0 -1.11082737487231]
 [0.0 0.0 0.0 ... 15283.0 -318.0 -2.08074330955963]
 ...
 [0.0 0.0 0.0 ... 1215.0 23.6999999999998 1.9506172839506]
 [0.0 0.0 0.0 ... 1184.0 4.79999999999995 0.405405405405417]
 [0.0 0.0 0.0 ... 1141.0 10.5 0.920245398773005]]


In [21]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [22]:
print(y)

[ 60  60  60 ... 124 124 124]


In [23]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [24]:
print(x_train)

[[0.0 0.0 0.0 ... 95.0 0.0 0.0]
 [0.0 0.0 0.0 ... 52.0 5.0 9.61538461538462]
 [0.0 0.0 0.0 ... 31.0 -7.0 -22.5806451612903]
 ...
 [0.0 0.0 0.0 ... 1252.5 51.5 4.11177644710578]
 [0.0 0.0 0.0 ... 98.0 0.0 0.0]
 [0.0 0.0 0.0 ... 351.0 -37.0 -10.5413105413105]]


In [25]:
print(x_test)

[[0.0 0.0 0.0 ... 30.0 -3.0 -10.0]
 [0.0 0.0 0.0 ... 10126.0 -641.0 -6.33023898874185]
 [0.0 0.0 0.0 ... 658.0 -4.0 -0.607902735562305]
 ...
 [0.0 0.0 0.0 ... 22.0 4.0 18.1818181818181]
 [0.0 0.0 0.0 ... 220.0 -10.0 -4.54545454545454]
 [0.0 0.0 0.0 ... 59.0 8.0 13.5593220338983]]


In [26]:
print(y_train)

[106  38  96 ... 124  98  73]


In [27]:
print(y_test)

[ 87  51 111 ...  58  58 122]


In [28]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:,3:])

ValueError: ignored

In [29]:
print(x_train)

[[0.0 0.0 0.0 ... 95.0 0.0 0.0]
 [0.0 0.0 0.0 ... 52.0 5.0 9.61538461538462]
 [0.0 0.0 0.0 ... 31.0 -7.0 -22.5806451612903]
 ...
 [0.0 0.0 0.0 ... 1252.5 51.5 4.11177644710578]
 [0.0 0.0 0.0 ... 98.0 0.0 0.0]
 [0.0 0.0 0.0 ... 351.0 -37.0 -10.5413105413105]]


In [30]:
print(x_test)

[[0.0 0.0 0.0 ... 30.0 -3.0 -10.0]
 [0.0 0.0 0.0 ... 10126.0 -641.0 -6.33023898874185]
 [0.0 0.0 0.0 ... 658.0 -4.0 -0.607902735562305]
 ...
 [0.0 0.0 0.0 ... 22.0 4.0 18.1818181818181]
 [0.0 0.0 0.0 ... 220.0 -10.0 -4.54545454545454]
 [0.0 0.0 0.0 ... 59.0 8.0 13.5593220338983]]
